Further changes to parser arguments
COVIDAnalytics/DELPHI pull request #61
Opened 2020-09-17 16:04 UTC by MichaelLLi

2020-09-17 16:18 UTC, hamzatazib requested changes
DELPHI_utils_V3_static.py: I had renamed fitcasesnd and fitcasesd things into cases_fit_data and deaths_fit_data for clarity for other people, can you please bring it back ? :)

2020-09-17 16:21 UTC, MichaelLLi commented
Done!

2020-09-17 17:00 UTC, sakshamsoni97 commented on DELPHI_model_V3.py
> +    list_tuples = [x for x in list_tuples if x[0] == "Oceania"]
I think this should be commented out like it was before.

2020-09-17 17:37 UTC, hamzatazib commented on DELPHI_model_V3.py
> +    list_tuples = [x for x in list_tuples if x[0] == "Oceania"]
yup comment this out plz

2020-09-18 03:29 UTC, hamzatazib requested changes

2020-09-18 03:29 UTC, hamzatazib commented on DELPHI_model_V3.py
> +
delete this extra space

2020-09-18 03:29 UTC, MichaelLLi commented on DELPHI_model_V3.py
> +    list_tuples = [x for x in list_tuples if x[0] == "Oceania"]
LOL but I only want to do Oceania

2020-09-18 03:33 UTC, hamzatazib commented on DELPHI_model_V3.py
> +    list_tuples = [x for x in list_tuples if x[0] == "Oceania"]
This is gonna be merged into master, no can do :(

2020-09-18 03:33 UTC, MichaelLLi commented on DELPHI_model_V3.py
> +
Done

2020-09-18 03:38 UTC, hamzatazib commented on DELPHI_model_V3.py
> +
Think you haven't pushed the one where you delete the extra space in line 80

2020-09-18 04:01 UTC, hamzatazib approved these changes

2020-09-18 04:02 UTC, merged