Adding separate script for comparing annealing and tnc performance
COVIDAnalytics/DELPHI pull request #62
Opened 2020-09-18 12:51 UTC by sakshamsoni97

2020-09-18 13:56 UTC, hamzatazib requested changes

2020-09-18 13:56 UTC, hamzatazib commented on DELPHI_model_V3.py
> +    past_prediction_date = "".join(str(datetime.now().date() - timedelta(days=14)).split("-"))
why days=14?

2020-09-18 13:56 UTC, hamzatazib commented on DELPHI_utils_V3_dynamic.py
> +def MAPE(a, b):
we already have an MAPE function in static, please remove this one

2020-09-18 13:56 UTC, hamzatazib commented on DELPHI_utils_V3_dynamic.py
> +def KL(a, b):
rename as kl_divergence, avoiding capital letters in functions/methods' names

2020-09-18 13:56 UTC, hamzatazib commented on DELPHI_utils_V3_dynamic.py
> +    def get_province(self, country, province, min_case_count=100):
Add docstrings

2020-09-18 13:56 UTC, hamzatazib commented on DELPHI_utils_V3_dynamic.py
> +    def compare_metric(self,
Add docstrings

2020-09-18 13:56 UTC, hamzatazib commented on DELPHI_utils_V3_dynamic.py
> +                    metric=KL,
Shouldn't it be "KL" not directly KL ? How does that even run ..?

2020-09-18 13:56 UTC, hamzatazib commented on DELPHI_utils_V3_dynamic.py
> +                    verbose=True):
for the verbose part, maybe feed a logger object to the functions instead of printing and create an extra folder in the logs/ folder like optimizers_comparison

2020-09-18 13:56 UTC, hamzatazib commented on DELPHI_utils_V3_dynamic.py
> +
remove extra space

2020-09-18 13:56 UTC, hamzatazib commented on DELPHI_compare.py
> +    help="Print messages or not? Enter 0/1"
shouldn't be printing but rather logging and should be default, so you can get rid of this argument :)

2020-09-18 13:56 UTC, hamzatazib commented on DELPHI_compare.py
> +TRAIN = arguments.run_model
call it RUN_MODEL for consistency (or call the input argument --train and -t)

2020-09-18 13:56 UTC, hamzatazib commented on DELPHI_compare.py
> +        an_select, an_metric, tnc_metric, an_mape = model_compare.compare_metric((continent, country, province), plot=PLOT_OPTION, verbose=VERBOSE)
rename variables from an to annealing for clarity for other readers

2020-09-18 13:56 UTC, hamzatazib commented on DELPHI_compare.py
> +    comparison_df = pd.DataFrame.from_dict(comparison_results)
rename df_comparison

2020-09-18 13:56 UTC, hamzatazib commented on DELPHI_compare.py
> +    f"Checked Annealing v/s TNC. Annealing performs better {annealing_count}/{comparison_df.shape[0]} \n"
needs a tab space for lines 149/150 (shouldn't be at same level as logging)

2020-09-18 14:09 UTC, sakshamsoni97 commented on DELPHI_utils_V3_dynamic.py
> +def MAPE(a, b):
That one seems to be Mean Abs Percent Error. We wanted Max Abs Percent error here. But I'll make the function names consistent.

2020-09-18 18:14 UTC, hamzatazib requested changes

2020-09-18 18:14 UTC, hamzatazib commented on DELPHI_compare.py
> +        annealing_select, annnealine_metric, tnc_metric, annealing_mape = model_compare.compare_metric((continent, country, province), plot=PLOT_OPTION)
typo: annnealine -> annealing

2020-09-18 18:14 UTC, hamzatazib commented on DELPHI_compare.py
> +        annealing_select, annnealine_metric, tnc_metric, annealing_mape = model_compare.compare_metric((continent, country, province), plot=PLOT_OPTION)
also change _mape with _max_ape to be clear

2020-09-18 18:14 UTC, hamzatazib commented on DELPHI_compare.py
remove extra space

2020-09-18 18:14 UTC, hamzatazib commented on DELPHI_compare.py
remove extra space

2020-09-18 18:14 UTC, hamzatazib commented on DELPHI_utils_V3_dynamic.py
> +        Computes the given metric for predictions with annealing and tnc and the MAPE for annealing.
specify Max APE

2020-09-18 18:14 UTC, hamzatazib commented on DELPHI_utils_V3_dynamic.py
> +        MAPE for annealing)
Max APE

2020-09-18 18:14 UTC, hamzatazib commented on DELPHI_utils_V3_dynamic.py
> +        mape = DELPHIModelComparison.max_ape(merged['True Value'], merged['Annealing Prediction'])
rename variable as max_ape

2020-09-18 18:14 UTC, hamzatazib commented on DELPHI_utils_V3_dynamic.py
> +        if metric is None:
problematic because if I input something else it'll raise a weird error. Instead of None should use "KL" by default and it should be either:
- Asserted that it's KL otherwise say nothing else is implemented
- Or asked as a Command Line Argument with the only choice possible being KL
Whichever you prefer (maybe assertion is easier and we'll avoid having too many arguments in CLI)

2020-09-18 18:14 UTC, hamzatazib commented on DELPHI_utils_V3_dynamic.py
> +            self.logger.info('MAPE for Annealing: ' + str(mape) + '. Threshold is ' + str(threshold))
Use f-strings: `f"Max APE for Annealing: {max_ape}. Threshold is {threshold}"`. Make sure you max_ape value is rounded at 3 significant digits.

2020-09-18 18:14 UTC, hamzatazib commented on DELPHI_utils_V3_dynamic.py
> +            self.logger.info('MAPE for Annealing: ' + str(mape) + '. Threshold is ' + str(threshold))
should also be a self.logger.debug() rather than info()

2020-09-18 20:32 UTC, sakshamsoni97 commented on DELPHI_compare.py
you mean between the two lines?

2020-09-18 20:52 UTC, sakshamsoni97 commented on DELPHI_utils_V3_dynamic.py
> +        if metric is None:
I see. I had kept it this way to let someone send any function as a parameter, you think we should restrict to only ones that are implemented in there?
I wasn't able to send KL divergence function as default parameter because I have implemented it as a static class method and that throws an error.

2020-09-20 05:04 UTC, hamzatazib approved these changes

2020-09-20 05:04 UTC, merged